-- =====================================================================
-- FOI Sentinel v2 — Phase 2b: Cortex Search services
-- Knowledge bases for RAG-grounded triage and response drafting.
-- =====================================================================
USE WAREHOUSE FOI_WH;
USE SCHEMA FOI.FOI_SENTINEL_V2;

CREATE OR REPLACE CORTEX SEARCH SERVICE COUNCIL_POLICY_SEARCH
  ON CONTENT
  ATTRIBUTES DOC_TITLE, DOC_TYPE, SECTION_REF, CATEGORY
  WAREHOUSE = FOI_WH
  TARGET_LAG = '1 hour'
  AS SELECT DOC_ID, DOC_TITLE, DOC_TYPE, SECTION_REF, CATEGORY, CONTENT FROM COUNCIL_POLICY_DOCS;

CREATE OR REPLACE CORTEX SEARCH SERVICE DISCLOSURE_SEARCH
  ON RESPONSE_SUMMARY
  ATTRIBUTES REFERENCE_NUMBER, TOPIC, REQUEST_SUMMARY, EXEMPTIONS_APPLIED
  WAREHOUSE = FOI_WH
  TARGET_LAG = '1 hour'
  AS SELECT DISCLOSURE_ID, REFERENCE_NUMBER, TOPIC, REQUEST_SUMMARY, RESPONSE_SUMMARY, EXEMPTIONS_APPLIED FROM DISCLOSURE_LOG;

CREATE OR REPLACE CORTEX SEARCH SERVICE CAMDEN_FOI_SEARCH
  ON DOCUMENT_TEXT
  ATTRIBUTES IDENTIFIER, DOCUMENT_TITLE, DOCUMENT_DATE
  WAREHOUSE = FOI_WH
  TARGET_LAG = '24 hour'
  AS SELECT IDENTIFIER, DOCUMENT_TITLE, DOCUMENT_DATE, DOCUMENT_TEXT FROM CAMDEN_FOI_RESPONSES;

-- Cross-authority precedent (WhatDoTheyKnow) — how other UK authorities have
-- handled comparable requests, grounded in real responses pulled from WDTK.
CREATE OR REPLACE CORTEX SEARCH SERVICE WDTK_PRECEDENT_SEARCH
  ON SNIPPET
  ATTRIBUTES AUTHORITY_NAME, THEME, LAW_USED, OUTCOME, EXEMPTIONS, REQUEST_TITLE, REQUEST_URL
  WAREHOUSE = FOI_WH
  TARGET_LAG = '24 hour'
  AS SELECT EVENT_ID, AUTHORITY_NAME, THEME, LAW_USED, OUTCOME, EXEMPTIONS,
            REQUEST_TITLE, REQUEST_URL, SNIPPET
     FROM WDTK_EVENT
     WHERE SNIPPET IS NOT NULL;

-- GLA disclosure log — full real request/response text from london.gov.uk.
-- Grounds drafting and exemption assessment in complete published responses.
CREATE OR REPLACE CORTEX SEARCH SERVICE GLA_DISCLOSURE_SEARCH
  ON RESPONSE_TEXT
  ATTRIBUTES REFERENCE_NUMBER, TITLE, REGIME, THEME, REQUEST_SUMMARY, RESPONSE_DATE, SOURCE_URL, AUTHORITY_NAME
  WAREHOUSE = FOI_WH
  TARGET_LAG = '24 hour'
  AS SELECT SOURCE_URL, REFERENCE_NUMBER, TITLE, REGIME, THEME, REQUEST_SUMMARY,
            RESPONSE_TEXT, RESPONSE_DATE, AUTHORITY_NAME
     FROM GLA_DISCLOSURE_LOG
     WHERE LENGTH(RESPONSE_TEXT) > 20;
