-- =====================================================================
-- FOI Sentinel v2 — Phase 2a: Migrate knowledge-base tables from v1
-- =====================================================================
USE WAREHOUSE FOI_WH;
USE SCHEMA FOI.FOI_SENTINEL_V2;

CREATE OR REPLACE TABLE FOI_LEGISLATION      AS SELECT * FROM FOI.FOI_SENTINEL.FOI_LEGISLATION;
CREATE OR REPLACE TABLE COUNCIL_POLICY_DOCS  AS SELECT * FROM FOI.FOI_SENTINEL.COUNCIL_POLICY_DOCS;
CREATE OR REPLACE TABLE DISCLOSURE_LOG       AS SELECT * FROM FOI.FOI_SENTINEL.DISCLOSURE_LOG;
CREATE OR REPLACE TABLE CAMDEN_FOI_RESPONSES AS SELECT * FROM FOI.FOI_SENTINEL.CAMDEN_FOI_RESPONSES;
