-- =====================================================================
-- FOI Sentinel v2 — SPCS infrastructure (mirrors HMLR 06_spcs_hitl)
-- Run as ACCOUNTADMIN. Idempotent.
-- =====================================================================
USE ROLE ACCOUNTADMIN;
USE DATABASE FOI;
USE SCHEMA FOI_SENTINEL_V2;

-- 1. Cost-controlled compute pool (XS, auto-suspend 2 min)
CREATE COMPUTE POOL IF NOT EXISTS FOI_SENTINEL_POOL
    MIN_NODES = 1
    MAX_NODES = 1
    INSTANCE_FAMILY = CPU_X64_XS
    AUTO_SUSPEND_SECS = 120
    AUTO_RESUME = TRUE
    COMMENT = 'FOI Sentinel v2 Streamlit UI - cost-controlled XS pool';

-- 2. Image repository
CREATE IMAGE REPOSITORY IF NOT EXISTS FOI.FOI_SENTINEL_V2.IMAGES
    COMMENT = 'Container images for FOI Sentinel SPCS service';

-- 3. Service role (the role the container runs as)
CREATE ROLE IF NOT EXISTS FOI_SENTINEL_SVC
    COMMENT = 'Service role used by the FOI Sentinel container';
GRANT USAGE ON COMPUTE POOL FOI_SENTINEL_POOL TO ROLE FOI_SENTINEL_SVC;
GRANT USAGE ON DATABASE FOI TO ROLE FOI_SENTINEL_SVC;
GRANT USAGE ON SCHEMA FOI.FOI_SENTINEL_V2 TO ROLE FOI_SENTINEL_SVC;
GRANT USAGE ON WAREHOUSE FOI_WH TO ROLE FOI_SENTINEL_SVC;
-- Read + write the case-management tables (app updates cases, logs events, drafts responses)
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA FOI.FOI_SENTINEL_V2 TO ROLE FOI_SENTINEL_SVC;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA FOI.FOI_SENTINEL_V2 TO ROLE FOI_SENTINEL_SVC;
GRANT SELECT ON ALL VIEWS IN SCHEMA FOI.FOI_SENTINEL_V2 TO ROLE FOI_SENTINEL_SVC;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FOI.FOI_SENTINEL_V2 TO ROLE FOI_SENTINEL_SVC;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA FOI.FOI_SENTINEL_V2 TO ROLE FOI_SENTINEL_SVC;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA FOI.FOI_SENTINEL_V2 TO ROLE FOI_SENTINEL_SVC;
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA FOI.FOI_SENTINEL_V2 TO ROLE FOI_SENTINEL_SVC;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA FOI.FOI_SENTINEL_V2 TO ROLE FOI_SENTINEL_SVC;
-- Cortex Search service usage (live search on Intake / Guidance)
GRANT USAGE ON CORTEX SEARCH SERVICE FOI.FOI_SENTINEL_V2.COUNCIL_POLICY_SEARCH TO ROLE FOI_SENTINEL_SVC;
GRANT USAGE ON CORTEX SEARCH SERVICE FOI.FOI_SENTINEL_V2.DISCLOSURE_SEARCH TO ROLE FOI_SENTINEL_SVC;
GRANT USAGE ON CORTEX SEARCH SERVICE FOI.FOI_SENTINEL_V2.CAMDEN_FOI_SEARCH TO ROLE FOI_SENTINEL_SVC;
-- Cortex LLM functions (COMPLETE / SENTIMENT) used by Intake, Studio and Guidance
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE FOI_SENTINEL_SVC;
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE FOI_SENTINEL_SVC;
GRANT ROLE FOI_SENTINEL_SVC TO ROLE ACCOUNTADMIN;

-- 4. Reviewer role (people allowed to open the UI)
CREATE ROLE IF NOT EXISTS FOI_REVIEWER COMMENT = 'Role allowed to use the FOI Sentinel UI service';
GRANT USAGE ON DATABASE FOI TO ROLE FOI_REVIEWER;
GRANT USAGE ON SCHEMA FOI.FOI_SENTINEL_V2 TO ROLE FOI_REVIEWER;
GRANT USAGE ON WAREHOUSE FOI_WH TO ROLE FOI_REVIEWER;
GRANT ROLE FOI_REVIEWER TO USER PADDY;

SHOW COMPUTE POOLS LIKE 'FOI_SENTINEL_POOL';
SHOW IMAGE REPOSITORIES IN SCHEMA FOI.FOI_SENTINEL_V2;
